<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.Sdk/14.0.2">
  <PropertyGroup>
    <Version>9.0.3.0</Version>
    <PackageProjectUrl>https://github.com/Neferith/sts_dalamud_plugin</PackageProjectUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
      <ProjectReference Include="..\STS.Domain\STS.Domain.csproj" />
      <Content Include="data.json">
          <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="MoonLogo_sharpened.png" />
  </ItemGroup>
</Project>