server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    # Toutes les routes non trouvées → index.html (routing Blazor)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Compression pour les fichiers WASM
    location ~* \.(wasm|dll|dat)$ {
        add_header Cache-Control "public, max-age=604800";
    }
}
