<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <OverrideHtmlAssetPlaceholders>true</OverrideHtmlAssetPlaceholders>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Markdig" Version="0.40.0" />
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.5" />
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.5" PrivateAssets="all" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\STS.Domain\STS.Domain.csproj" />
        <ProjectReference Include="..\STS.Domain.User\STS.Domain.User.csproj" />
        <ProjectReference Include="..\STS.Domain.Character\STS.Domain.Character.csproj" />
        <ProjectReference Include="..\STS.Domain.Content\STS.Domain.Content.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Folder Include="Pages\CharacterCreate\" />
        <Folder Include="Pages\CharacterDetail\" />
        <Folder Include="Shared\" />
    </ItemGroup>

    <ItemGroup>
      <None Include="wwwroot\css\login-modal.css" />
    </ItemGroup>

</Project>