<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>Sts.Admin</RootNamespace>
        <AssemblyName>STS.Admin</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Markdig" Version="0.40.0" />
        <ProjectReference Include="..\STS.Domain\STS.Domain.csproj" />
        <ProjectReference Include="..\STS.Domain.Content\STS.Domain.Content.csproj" />
        <ProjectReference Include="..\STS.Domain.User\STS.Domain.User.csproj" />
        <ProjectReference Include="..\STS.Domain.Character\STS.Domain.Character.csproj" />
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="8.0.0" />
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="8.0.0" PrivateAssets="all" />
    </ItemGroup>

</Project>
