<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <RootNamespace>Sts.Discord</RootNamespace>
    <AssemblyName>STS.Discord</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\STS.Domain.Content\STS.Domain.Content.csproj" />
  </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Discord.Net" Version="3.15.3" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.0" />
        <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="8.0.0" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="UseCases\" />
    </ItemGroup>

</Project>
