<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <RootNamespace>Sts.Domain.Content</RootNamespace>
    <AssemblyName>STS.Domain.Content</AssemblyName>
  </PropertyGroup>

</Project>
